import { useEffect, useState } from "react";
import { Award, LogOut, Save, User } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/contexts/AuthContext";
import { getProfile, updateProfile } from "@/services/profiles";
import { toast } from "sonner";

export default function Profile(){const {user,signOut}=useAuth();const [name,setName]=useState("");const [bio,setBio]=useState("");const [points,setPoints]=useState(0);const [busy,setBusy]=useState(false);useEffect(()=>{if(user)getProfile(user.id).then(p=>{setName(p.display_name||"");setBio(p.bio||"");setPoints(p.points||0)}).catch(()=>{})},[user]);async function save(){if(!user)return;setBusy(true);try{await updateProfile(user.id,{display_name:name,bio});toast.success("Profile updated")}catch(e:any){toast.error(e.message||"Could not update profile")}finally{setBusy(false)}}return <div className="mx-auto max-w-2xl space-y-5"><div className="glass-card-elevated p-6 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-primary/10 text-2xl font-black text-primary">{(name||user?.email||"U").slice(0,2).toUpperCase()}</div><h1 className="mt-3 text-xl font-black">{name||"Citizen"}</h1><p className="text-sm text-muted-foreground">{user?.email}</p><div className="mx-auto mt-3 inline-flex items-center gap-1 rounded-full bg-primary/10 px-3 py-1 text-sm font-bold text-primary"><Award size={15}/>{points} points</div></div><div className="glass-card p-6 space-y-4"><div><label className="text-xs font-semibold text-muted-foreground">Display name</label><Input className="mt-1" value={name} onChange={e=>setName(e.target.value)}/></div><div><label className="text-xs font-semibold text-muted-foreground">Bio</label><Input className="mt-1" value={bio} onChange={e=>setBio(e.target.value)} placeholder="Why you care about a cleaner city"/></div><Button onClick={save} disabled={busy} className="w-full gap-2"><Save size={16}/>{busy?"Saving…":"Save profile"}</Button></div><Button variant="outline" onClick={async()=>{await signOut()}} className="w-full gap-2 text-destructive"><LogOut size={16}/>Sign out</Button><div className="glass-card p-5 text-sm text-muted-foreground"><User className="mb-2 text-primary" size={18}/> Your profile and reports are protected by Supabase authentication and row-level security.</div></div>}
