import { ArrowRight, Camera, CheckCircle2, MapPin, ShieldCheck, Sparkles, Trophy } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";

export default function Landing() {
  return <div className="min-h-screen bg-background">
    <header className="border-b bg-background/90 backdrop-blur"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4"><div className="flex items-center gap-2 font-extrabold"><span className="grid h-9 w-9 place-items-center rounded-xl gradient-hero">🌱</span>CleanSnap</div><Link to="/auth"><Button variant="outline">Sign in</Button></Link></div></header>
    <main className="mx-auto max-w-6xl px-4">
      <section className="grid items-center gap-10 py-14 md:grid-cols-2 md:py-20"><div><div className="mb-4 inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1 text-xs font-bold text-primary"><Sparkles size={14}/> AI-powered civic cleanup</div><h1 className="text-4xl font-black tracking-tight sm:text-6xl">Make your city cleaner.<span className="block text-gradient">One report at a time.</span></h1><p className="mt-5 max-w-xl text-base text-muted-foreground sm:text-lg">Snap a cleanliness issue, let AI verify it, share the location and track the report until it gets resolved.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/auth"><Button size="lg" className="gradient-hero border-0 gap-2">Report an issue <ArrowRight size={17}/></Button></Link><a href="#how"><Button size="lg" variant="outline">How it works</Button></a></div></div><div className="glass-card-elevated overflow-hidden p-5"><div className="rounded-2xl bg-secondary p-5"><div className="mb-4 flex items-center justify-between"><span className="font-bold">Live community impact</span><span className="rounded-full bg-primary/10 px-2 py-1 text-xs text-primary">AI verified</span></div><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-card p-4"><Camera className="text-primary" size={20}/><p className="mt-3 text-2xl font-black">∞</p><p className="text-xs text-muted-foreground">Reports possible</p></div><div className="rounded-xl bg-card p-4"><MapPin className="text-primary" size={20}/><p className="mt-3 text-2xl font-black">GPS</p><p className="text-xs text-muted-foreground">Location based</p></div><div className="rounded-xl bg-card p-4"><ShieldCheck className="text-primary" size={20}/><p className="mt-3 text-2xl font-black">AI</p><p className="text-xs text-muted-foreground">Verification</p></div><div className="rounded-xl bg-card p-4"><Trophy className="text-primary" size={20}/><p className="mt-3 text-2xl font-black">⭐</p><p className="text-xs text-muted-foreground">Earn rewards</p></div></div></div></div></section>
      <section id="how" className="py-10"><h2 className="text-2xl font-black">How CleanSnap works</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{[[Camera,"1. Snap","Upload a photo of a real cleanliness issue."],[ShieldCheck,"2. Verify","AI identifies waste type and severity."],[CheckCircle2,"3. Track","Submit, follow status and earn points."]].map(([Icon,title,body]: any)=><div className="glass-card p-5" key={title}><Icon className="text-primary" size={24}/><h3 className="mt-4 font-bold">{title}</h3><p className="mt-2 text-sm text-muted-foreground">{body}</p></div>)}</div></section>
    </main>
  </div>;
}
